@echo off
echo Installing requirements...
pip install -r requirements.txt
echo Converting Icon...
python convert_icon.py
echo Building Media Yantra...
python -m PyInstaller --noconfirm --onedir --windowed --icon="assets\icon.ico" --collect-binaries imageio_ffmpeg --name "Media Yantra" "main.py"
echo Build Complete!
